package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 *
 */
@WebService(name = "HelloWorld", targetNamespace = "http://ws/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface HelloWorld {


    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHelloWorldAsString", targetNamespace = "http://ws/", className = "client.GetHelloWorldAsString")
    @ResponseWrapper(localName = "getHelloWorldAsStringResponse", targetNamespace = "http://ws/", className = "client.GetHelloWorldAsStringResponse")
    @Action(input = "http://ws/HelloWorld/getHelloWorldAsStringRequest", output = "http://ws/HelloWorld/getHelloWorldAsStringResponse")
    public String getHelloWorldAsString(@WebParam(name = "arg0", targetNamespace = "") String arg0);

}